services:
  app:
    build:
      context: .
      dockerfile: Docker/Dockerfile
    container_name: app-service-finance
    networks:
      - financialsystems
    restart: always
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - mysql
    # - mongo
    command: npm run start:dev

  mysql:
    image: mysql:8
    container_name: db-service-finance
    restart: always
    volumes:
      - /home/oliveira/Project/volumes-docker/finance-service-api/mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    ports:
      - 3307:3306

  # mongo:
  #   image: mongo
  #   container_name: mongo-service-finance
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: root
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - /opt/mongo_data:/var/lib/mongo

  # redis:
  #   image: redis:latest
  #   container_name: redis-service-finance
  #   restart: always
  #   ports:
  #     - 6379:6379
  #   volumes:
  #     - /opt/redis_data:/data
  #   command: ['redis-server', '--appendonly', 'yes']

networks:
  financialsystems:
    external: true

