services:
  app:
    build:
      context: .
      dockerfile: Docker/DockerfileDev
    container_name: app-service-finance
    restart: always
    volumes:
      - .:/var/www
    ports:
      - 3001:3001
      # - 5000:5000
      # - 9230:9229
    env_file:
      - .env
    # depends_on:
    # - mysql
    # - mongo
    command: npm run start:dev

  mysql:
    image: mysql
    container_name: db-service-finance
    restart: unless-stopped
    volumes:
      - /opt/mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: configuration
      MYSQL_USER: userAdmin
      MYSQL_PASSWORD: acesso
      MYSQL_ROOT_PASSWORD: acesso
    ports:
      - 3307:3306

  mongo:
    image: mongo
    container_name: mongo-service-finance
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - /opt/mongo_data:/data/db

networks:
  default:
    name: madeiramadeira
