services:
  app:
    build:
      context: .
      dockerfile: ./Docker/Dockerfile
    container_name: finance-service-api
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
    command: npm run start:dev

  db:
    image: postgres:15
    container_name: db-finance-service-api
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
